name: Check for Paper changes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  check:
    name: Check for Paper changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Configure Git Identity
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: poetry install
      - run: "poetry run python3 paper-differ/__main__.py --repo ${{ secrets.REPO_PATH_WITH_CREDS }}"
