name: Check for Paper changes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  check:
    name: Check for Paper changes
    runs-on: ubuntu-latenst
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
      - run: poetry install
      - run: "poetry run 'python3 paper-differ/__main__.py'"